### ISSUE TITLE
truncation widget breaks CSS formatting

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1552]
The new truncation widget does not correctly apply CSS style to both "halves" of the truncated text.

Snapshot showing example, from the "about" link which has been split into two sub-elements:
![image.png](https://images.zenhubusercontent.com/5af38d3b4b5806bc2bd28ea9/745e8cdc-fda4-4ef8-9797-cff1917158c4)

It looks like the left side correctly inherits the style, but the right side does not.

**Comment by seve** [comment]
Truncation grabs the styles for the second half from the provided child since the element simplicity gets its styles from the `<a>` tag there isn't an explicit color tag given to Truncation and it uses the `initial` color for the second half.

This could be fixed by giving the `<a>` explicit color styling, but that's not quite addressing the problem and we might run into more issues later.

Any thoughts @colinmegill @tihuan ?

**Comment by tihuan** [comment]
Ahh thanks raising this bug, @bkmartinjr !

@seve yeah I see that the explicit `color` rules in our truncation is causing the issue. Testing an idea now. Will let you all know how it goes!

**Comment by tihuan** [comment]
OK I think I got a solution: https://codepen.io/tihuan/pen/dyGGPRq 😄 !

The changes I made are:

```html
<a href="https://www.google.com"> ////////// Added this to test link style
<span class="split">
  <span class="first">
    really long-file-name-
  </span>
  <span class="second">
    ////////// wrapping this one in a span and add a class "second--space"
    <span class="second--space">123456789-abcdefghijklmnopqrstuvwxyz.txt</span>

    ////////// Add a class "second--content"
    <span class="second--content">
      123456789-abcdefghijklmnopqrstuvwxyz.txt
    </span>
  </span>
</span>
</a>
```

And then CSS:
```css
.second {
  position: relative;
  overflow: hidden;
  white-space:nowrap;
}

.second--space {
  color: transparent;
}

.second--content {
  position: absolute;
  right: 0;
}
```

Essentially, the problem we have is that originally we have:

```css
.second > span {
  position: absolute;
  right: 0;
  /* this is needed to counter the color: transparent set at the parent "second" */
  color: initial;
}
```

So we remove `color: transparent" from class: `"second"`, and move it into `"second--space"`, and then `second--content` won't need `color: initial` and will correctly inherit the color from `<a />`

Regarding `client/src/components/leftSidebar/topLeftLogoAndTitle.js:70`:

```ts
<Truncate>
  <a
      style={{ width: 185 }}
      href={aboutURL}
      data-testid="header"
      target="_blank"
      rel="noopener noreferrer"
    >
      {datasetTitle}
    </a>
</Truncate>
```

Maybe we can wrap `<Truncate />` in `<a />` instead? Like so:

```ts
<a
  style={{ width: 185 }}
  href={aboutURL}
  data-testid="header"
  target="_blank"
  rel="noopener noreferrer"
>
  <Truncate>
    <span>{datasetTitle}</span>
  </Truncate>
</a>
```

I'm deep in updating smoke test now, so @seve can you help taking this over and apply the changes to our code please 🙏 ?? Thank you!!
