### ISSUE TITLE
Update github compatibility workflows to match new requirements

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#2331]
We do not need to test for compatibility with anndata/scanpy versions we do not support.

from the current compatibility_tests.yml:
```
    strategy:
      matrix:
        python-version: [3.6, 3.7] # As of Oct 2020 Anndata is not compatible with 3.8
        anndata-version: [0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5]
        test-suite: [smoke-test, smoke-test-annotations]
```

I recommend:
* Python 3.6, 3.7, 3.8 (3.9 is not quite ready, but there is another bug for that #2299)
* AnnData 0.7.6
